### ISSUE TITLE
pkl files from dorothea not distributed with package.

### ISSUE THREAD

**Issue by ilibarra** [saezlab/dorothea-py#1]
Hello Pau,

Thanks for implementing this. Installation works, but execution of main tutorial script fails. I think the pkl files were not distributed or downloaded in the main tutorial. Could you please take a look? They should be the `rds` files converted to `pkl` ones I suppose. E.g.

```
%%time
# Read Dorothea Regulons for Human
dorothea_hs = dorothea.load_regulons(['A','B','C'])

# Compute SCIRA scores, returns an AnnData object with TF activities intead of gene expresion
tf_adata = dorothea.run_scira(adata, dorothea_hs, norm='c')
```
```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<timed exec> in <module>

~/miniconda3/envs/mypython3/lib/python3.7/site-packages/dorothea/dorothea.py in load_regulons(levels, organism)
     17 
     18     # Open pickle object
---> 19     df = pickle.load(open(path, "rb" ))
     20 
     21     #Filter by levels of confidence

FileNotFoundError: [Errno 2] No such file or directory: '~/miniconda3/envs/mypython3/lib/python3.7/site-packages/dorothea/data/dorothea_hs.pkl'
```

Thanks!

**Comment by PauBadiaM** [comment]
Hi @ilibarra,

Thank you for trying it out. Sorry that I did not answer before, somehow I forgot to activate notifications for this repo.
Yes, due to a mistake in the `.gitignore` is was not uploading the `pkl` files. I changed that and now they are available.
Now to install it again you should do:
```
pip uninstall dorothea
pip install git+https://github.com/saezlab/dorothea-py.git
```
Please, let me know if this works.

**Comment by ilibarra** [comment]
It is working now. Thanks!
