### ISSUE TITLE
Can't load regulons

### ISSUE THREAD

**Issue by anikaliu** [saezlab/dorothea-py#6]
Hello:)
I'm having trouble loading regulons (for all levels/organisms) and it seems to be related to the filepath? Is this something I can fix from my side?

Cheers,
Anika
```
>>> import dorothea
>>> regulons = dorothea.load_regulons(levels=['A','B','C'],organism='Mouse')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/al862/anaconda3/envs/scanpy_cellrank/lib/python3.8/site-packages/dorothea/dorothea.py", line 57, in load_regulons
    df = pickle.load(open(path, "rb" ))
  File "pandas/_libs/internals.pyx", line 572, in pandas._libs.internals.BlockManager.__cinit__
TypeError: __cinit__() takes at least 2 positional arguments (0 given)
```

**Comment by PauBadiaM** [comment]
Hi @anikaliu !

Wow this is a new one haha Can I ask what versions of python, pandas and pickle are you running?

Cheers!

**Comment by anikaliu** [comment]
Hey @PauBadiaM,

Haha yes sorry about that:D Thanks for the pointer to package versions! I'm using Python 3.8.5 but found [here](https://exerror.com/cannot-read-pickle-file-in-cloud-run-app-typeerror-__cinit__-takes-at-least-2-positional-arguments/
) that the pandas version was the problem. It was 1.3.0 before and now it's working fine after upgrading to 1.3.1. :)

**Comment by PauBadiaM** [comment]
Perfect! I will add pandas 1.3.1 as a requirement.
